hub:
  mass: 0.02
  size:
    x: 0.014
    y: 0.014
    z: 0.0705
  dx: 0.135 #-0.5 # Can we use variable inside yaml files? ${-base_length/2*0.69}
  dy: 0.0
  dz: 0.073
  mesh: 'caster_wheel_v3.stl'

wheel:
  #  <xacro:property name="caster_wheel_mass" value="0.5" /> <!-- in kg-->
  mass: 0.5        # Wheel mass in Kg
  radius: 0.0175     # Wheel radius in m
  length: 0.01      # Wheel length in m, considering is as a cylinder
  # mesh: 'caster_wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
  mesh: ''          # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.035
  dx: 0.016  # ${-caster_base_size/2.0*0.8}
  dy: -1 # TODO unused
  dz: -0.0705 # TODO can we use ${-caster_base_size} inside yaml?