wheel:
  mass: 0.396       # Wheel mass in Kg
  radius: 0.05      # Wheel radius in m
  length: 0.025     # Wheel length in m, considering is as a cylinder
  mesh: 'right_wheel_v3.stl' # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.0     # Offset distance, in meters, from the outer face of the base to the center of the wheel.
  # The outer face of the base is the reference so, if the wheels are inside the base the value must be
  # positive. If the wheels are outside, must be negative.
  y_offset: 0.0     # Offset distance, in meters, from the outer face of the base to the inner face of the wheel.
  z_offset: 0.035     # Offset distance, in meters, from the bottom face of the base to the center of the wheel.