# Move base node parameters. 
# For full documentation of the parameters in this file, please see
#
#  http://wiki.ros.org/move_base#Parameters
#

global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: true
  transform_tolerance: 0.5
  inflation_radius: 0.25
  cost_scaling_factor: 1.3
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}