# Move base node parameters. 
# For full documentation of the parameters in this file, please see
#
#  http://wiki.ros.org/move_base#Parameters
#

costmap:
  global_frame    : map
  robot_base_frame: base_footprint
  map_type        : costmap

  update_frequency    : 5.0
  publish_frequency   : 0.0
  static_map          : true
  transform_tolerance : 0.5     # default 0.3
  resolution          : 0.1     # default 0.05

  inflation_radius    : 0.25    # default 0.55
  cost_scaling_factor : 1.3     # default 10

  robot_radius      : 0.176
  footprint_padding : 0.0

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
